MAP_FILE = File.join(File.dirname(__FILE__), 'LongerMap.json');
#MAP_FILE = File.join(File.dirname(__FILE__), 'TinyMap.json');
FRAME_DELAY=16 
TILE_SIZE=70
OBSTACLE="Obstacle"
LADDER="Ladder"
WALKING_SPEED=5
JUMPING_SPEED=20
JUMPING_DECELERATION=2
CLIMBING_SPEED=3