# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ed530451c1cdaba2d06e2b6c7698b30b6639e1611b7ac2e4cbbc31d6689b2e083874dff258075f82e621cb0b4a29c87adb40f7c3c9dd652e5ae67346f5b45b

test:
  secret_key_base: 3d8616ed8a067b2ec2dc3ef1762a671337000d1c3637b1504209c1f18133ccaa3ed6596e0f7e825c8417095fbb2d4169fac0ebe45f3c6958e89cfe17586a451d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
